# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('Lat', models.CharField(max_length=200)),
                ('Long', models.CharField(max_length=200)),
            ],
        ),
    ]
