# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_less', '0002_userloc_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=200)),
                ('users', models.CharField(max_length=200)),
            ],
        ),
    ]
